
doc:
		xelatex moran_derivation	
		xelatex moran_derivation

figure1:
	python3 ../../src/viz.py -figure1 -o ../../plots/figure1.eps




clean:
		rm -f *.log *.out *.aux *.pdf *.bak *.toc *.vrb *.nav *.snm
