
moran_derivation:
		xelatex moran_derivation	
		xelatex moran_derivation

moran_figure1:
	# TODO : if the libraries aren't there, make sure to build them
	python3 ../src/viz.py -figure1 -o ../plots/moran_figure1.eps

moran_figure2:
	echo("Coming Soon!")

dtwf_properties:
	xelatex dtwf_offspring
	xelatex dtwf_offspring







clean:
		rm -f *.log *.out *.aux *.pdf *.bak *.toc *.vrb *.nav *.snm
